version: 2
jobs:
  build:
    context: demo
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: $PG_USER
          POSTGRES_DB: circle_test

    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mvn test
      - run: mvn checkstyle:checkstyle

  lint:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run: mvn checkstyle:checkstyle

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - lint

